### ISSUE TITLE
IGW Crash on Startup (in modpack)

### ISSUE THREAD

**Issue by Xiaminou** [MineMaarten/IGW-mod#28] opened 2015-06-14 11:55 UTC
IGW: 1.1.3-18
Forge: 1403
Pastebin: http://pastebin.com/yNVAYD1L

**Comment by sandalle** [comment] 2015-06-16 22:01
Dupe of #26 ?

**Comment by Xiaminou** [comment] 2015-06-16 22:32
Maybe, then how do I fix it? it's been 2 weeks, has there been any new version of IGW to fix the bugs?

**Comment by sandalle** [comment] 2015-06-16 22:38
I disabled the IGW-Mod support in the only mod using it for [Modderation: Permabanned](http://www.technicpack.net/modpack/details/modderation-permabanned-edition.449941), Extra Cells 2, and then removed the IGW-Mod jar from client and server (server is optional anyways) during my testing.

**Comment by Xiaminou** [comment] 2015-06-16 22:42
Well yeah, right now I'm playing without it, but I need it for Pneumaticraft.

**Closed** 2015-06-29 13:13 UTC

**Comment by MineMaarten** [comment] 2015-06-29 13:14
I'm very sorry for the delay people :|
